import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const RUNNER = path.join(ROOT, 'scripts', 'run-full-regression.mjs');

assert.ok(fs.existsSync(RUNNER), 'scripts/run-full-regression.mjs should exist');

const source = fs.readFileSync(RUNNER, 'utf8');

assert.match(source, /PETBANK_BASE_URL/, 'runner should provide PETBANK_BASE_URL support');
assert.match(source, /gameplay_core_flows_simulation\.mjs/, 'runner should include core gameplay simulation');
assert.match(source, /full_game_loop_simulation\.mjs/, 'runner should include full game loop simulation');
assert.match(source, /extended_whole_game_progression_simulation\.mjs/, 'runner should include extended whole-game progression simulation');
assert.match(source, /profile_isolation_journey_simulation\.mjs/, 'runner should include profile isolation journey simulation');
assert.match(source, /whole_game_completion_audit\.mjs/, 'runner should include whole-game completion audit');
assert.match(source, /cross_surface_journey_simulation\.mjs/, 'runner should include cross-surface journey simulation');
assert.match(source, /parent_light_modules_simulation\.mjs/, 'runner should include parent light modules simulation');
assert.match(source, /cloud_family_social_pk_simulation\.mjs/, 'runner should include cloud family/social simulation');
assert.match(source, /edge_states_standalone_simulation\.mjs/, 'runner should include edge states simulation');
assert.match(source, /leaderboard_standalone_simulation\.mjs/, 'runner should include leaderboard simulation');
assert.match(source, /audio_battle_feedback_contract\.test\.mjs/, 'runner should include audio contract test');
assert.match(source, /battle_milestones_contract\.test\.mjs/, 'runner should include battle milestones contract');
assert.match(source, /pk_brawl_shared_design_contract\.test\.mjs/, 'runner should include pk brawl shared design contract');
assert.match(source, /pk_brawl_shared_experience_contract\.test\.mjs/, 'runner should include pk brawl shared experience contract');
assert.match(source, /social_two_pet_visual_contract\.test\.mjs/, 'runner should include social two-pet visual contract');
assert.match(source, /social_walk_profile_switch_info_contract\.test\.mjs/, 'runner should include social walk profile-switch contract');
assert.match(source, /route_aware_shell_contract\.test\.mjs/, 'runner should include route-aware shell contract');
assert.match(source, /test_family_review_contract\.py/, 'runner should include family review contract');
assert.match(source, /test_activity_feed_contract\.py/, 'runner should include activity feed contract');
assert.match(source, /test_friend_home_visit_page_contract\.py/, 'runner should include friend home visit page contract');
assert.match(source, /test_friend_house_preview_contract\.py/, 'runner should include friend house preview contract');
assert.match(source, /test_registration_invite_contract\.py/, 'runner should include registration invite contract');
assert.match(source, /test_registration_invite_management_contract\.py/, 'runner should include registration invite management contract');
assert.match(source, /test_friend_graph_contract\.py/, 'runner should include friend graph contract');
assert.match(source, /test_house_visit_contract\.py/, 'runner should include house visit contract');
assert.match(source, /test_profile_sync_contract\.py/, 'runner should include profile sync contract');
assert.match(source, /test_multi_child_sync_contract\.py/, 'runner should include multi-child sync contract');
assert.match(source, /test_children_schema_contract\.py/, 'runner should include children schema contract');
assert.match(source, /test_child_access_controls_contract\.py/, 'runner should include child access controls contract');
assert.match(source, /test_async_pk_results_contract\.py/, 'runner should include async pk results contract');
assert.match(source, /test_child_social_profile_contract\.py/, 'runner should include child social profile contract');
assert.match(source, /test_cloud_config_persistence_contract\.py/, 'runner should include cloud config persistence contract');
assert.match(source, /test_cloud_diagnostics_contract\.py/, 'runner should include cloud diagnostics contract');
assert.match(source, /test_cloud_loader_pages_contract\.py/, 'runner should include cloud loader pages contract');
assert.match(source, /test_cloud_sync_contract\.py/, 'runner should include cloud sync contract');
assert.match(source, /test_family_social_ops_contract\.py/, 'runner should include family social ops contract');
assert.match(source, /test_family_social_scope_contract\.py/, 'runner should include family social scope contract');
assert.match(source, /test_household_contract\.py/, 'runner should include household contract');
assert.match(source, /test_household_invite_issue_contract\.py/, 'runner should include household invite issue contract');
assert.match(source, /test_household_peer_social_contract\.py/, 'runner should include household peer social contract');
assert.match(source, /test_social_walk_action_contract\.py/, 'runner should include social walk action contract');
assert.match(source, /test_social_walk_invite_flow_contract\.py/, 'runner should include social walk invite flow contract');
assert.match(source, /test_home_background_theme_contract\.py/, 'runner should include home background theme contract');
assert.match(source, /test_walk_scene_adventure_contract\.py/, 'runner should include walk scene adventure contract');
assert.match(source, /test_explore_rescue_card_contract\.py/, 'runner should include explore rescue card contract');
assert.match(source, /test_home_dashboard_nav_contract\.py/, 'runner should include home dashboard nav contract');
assert.match(source, /test_pet_walk_page_contract\.py/, 'runner should include pet walk page contract');
assert.match(source, /test_points_exchange_cards_contract\.py/, 'runner should include points exchange cards contract');

console.log('PASS regression runner contract');
